package modelo;


// Generated 26-ago-2017 15:00:10 by Hibernate Tools 4.3.1



/**
 * Categorias generated by hbm2java
 */
public class Categorias  implements java.io.Serializable {


     private int codcategoria;
     private String descripcion;
    
    public Categorias() {
    }

	
    
   
    public int getCodcategoria() {
        return this.codcategoria;
    }
    
    public void setCodcategoria(int codcategoria) {
        this.codcategoria = codcategoria;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    




}


