package modelo;

import java.sql.SQLException;


// Generated 26-ago-2017 15:00:10 by Hibernate Tools 4.3.1




/**
 * Ciudades generated by hbm2java
 */
public class Ciudades  implements java.io.Serializable {


     private String codciudad;
     private String nombreciudad;
     private String codprovincia;
     
     private Provincia provincia;

    public Ciudades() {
    }

	
   
   
    public String getCodciudad() {
        return this.codciudad;
    }
    
    public void setCodciudad(String codciudad) {
        this.codciudad = codciudad;
    }
    public String getNombreciudad() {
        return this.nombreciudad;
    }
    
    public void setNombreciudad(String nombreciudad) {
        this.nombreciudad = nombreciudad;
    }

    public Provincia getProvincia() {
        return provincia;
    }

    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }

    public String getCodprovincia() {
        return codprovincia;
    }

    public void setCodprovincia(String codprovincia) throws SQLException {
        provincia= new ProvinciaDAO().obtenerProvincia(codprovincia);
        this.codprovincia = codprovincia;
    }
   




}


