package modelo;

// Generated 26-ago-2017 15:00:10 by Hibernate Tools 4.3.1
import java.sql.SQLException;

/**
 * Detallemovimiento generated by hbm2java
 */
public class Detallemovimiento implements java.io.Serializable {

    private Responsables responsables;
    private long codmovimiento;
    private String codarticilo;
    private String nfactura;
    private Articulos articulos;
    private Movimientos movimientos;
    private int orden;
    private double cantidad;
    private double costo;

    public Detallemovimiento() {

    }

    public long getCodmovimiento() {
        return this.codmovimiento;
    }

    public void setCodmovimiento(long codmovimiento) throws SQLException {
        movimientos = new MovimientoDAO().obtenerMovimiento(codmovimiento);
        this.codmovimiento = codmovimiento;
    }

    public Articulos getArticulos() {
        return this.articulos;
    }

    public void setArticulos(Articulos articulos) {
        codarticilo=articulos.getCodarticulo();
        this.articulos = articulos;
    }

    public Movimientos getMovimientos() {
        return this.movimientos;
    }

    public void setMovimientos(Movimientos movimientos) {
        this.movimientos = movimientos;
    }

    public int getOrden() {
        return this.orden;
    }

    public void setOrden(int orden) {
        this.orden = orden;
    }

    public double getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }

    public double getCosto() {
        return this.costo;
    }

    public void setCosto(double costo) {
        this.costo = costo;
    }

    public String getCodarticilo() {
        return codarticilo;
    }

    public void setCodarticilo(String codarticilo) throws SQLException {
        ArticuloDAO dt = new ArticuloDAO();
        articulos = dt.obtenerArticulo(codarticilo);
        this.codarticilo = codarticilo;
    }

    public String getNfactura() {
        return nfactura;
    }

    public void setNfactura(String nfactura) {
        this.nfactura = nfactura;
    }

    public Responsables getResponsables() {
        return responsables;
    }

    public void setResponsables(Responsables responsables) {
        this.responsables = responsables;
    }
    
    
    

}
