package modelo;


// Generated 26-ago-2017 15:00:10 by Hibernate Tools 4.3.1

import java.sql.Date;





/**
 * Movimientos generated by hbm2java
 */
public class Movimientos  implements java.io.Serializable {


     private long codmovimiento;
     private Responsables responsables;
     private Tipomovimiento tipomovimiento;
     
     private String identificacion;
     private String tiporesponsable;
     
     private String codtipomovimiento;
     private char naturaleza;
     private String codusuario;
     private String concepto;
     private Date fechamovimiento;
     private Double totalmovimiento;
     private Date fechahoraingreso;
     private Date fechahoraactualizacion;
     private Date fechahoraanulacion;
     private String usuarioanulacion;
     private String usuarioaactualizacion;
     private Character estado;
     private Detallemovimiento detallemovimiento;
     
     private String nfactura;

    public Movimientos() {
    }

	
    
   
    public long getCodmovimiento() {
        return this.codmovimiento;
    }
    
    public void setCodmovimiento(long codmovimiento) {
        this.codmovimiento = codmovimiento;
    }
    public Responsables getResponsables() {
        return this.responsables;
    }
    
    public void setResponsables(Responsables responsables) {
        this.responsables = responsables;
    }
    public Tipomovimiento getTipomovimiento() {
        return this.tipomovimiento;
    }
    
    public void setTipomovimiento(Tipomovimiento tipomovimiento) {
        this.tipomovimiento = tipomovimiento;
    }
    public char getNaturaleza() {
        return this.naturaleza;
    }
    
    public void setNaturaleza(char naturaleza) {
        this.naturaleza = naturaleza;
    }
    public String getCodusuario() {
        return this.codusuario;
    }
    
    public void setCodusuario(String codusuario) {
        this.codusuario = codusuario;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public Date getFechamovimiento() {
        return this.fechamovimiento;
    }
    
    public void setFechamovimiento(Date fechamovimiento) {
        this.fechamovimiento = fechamovimiento;
    }
    public Double getTotalmovimiento() {
        return this.totalmovimiento;
    }
    
    public void setTotalmovimiento(Double totalmovimiento) {
        this.totalmovimiento = totalmovimiento;
    }
    public Date getFechahoraingreso() {
        return this.fechahoraingreso;
    }
    
    public void setFechahoraingreso(Date fechahoraingreso) {
        this.fechahoraingreso = fechahoraingreso;
    }
    public Date getFechahoraactualizacion() {
        return this.fechahoraactualizacion;
    }
    
    public void setFechahoraactualizacion(Date fechahoraactualizacion) {
        this.fechahoraactualizacion = fechahoraactualizacion;
    }
    public Date getFechahoraanulacion() {
        return this.fechahoraanulacion;
    }
    
    public void setFechahoraanulacion(Date fechahoraanulacion) {
        this.fechahoraanulacion = fechahoraanulacion;
    }
    public String getUsuarioanulacion() {
        return this.usuarioanulacion;
    }
    
    public void setUsuarioanulacion(String usuarioanulacion) {
        this.usuarioanulacion = usuarioanulacion;
    }
    public String getUsuarioaactualizacion() {
        return this.usuarioaactualizacion;
    }
    
    public void setUsuarioaactualizacion(String usuarioaactualizacion) {
        this.usuarioaactualizacion = usuarioaactualizacion;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Detallemovimiento getDetallemovimiento() {
        return this.detallemovimiento;
    }
    
    public void setDetallemovimiento(Detallemovimiento detallemovimiento) {
        this.detallemovimiento = detallemovimiento;
    }

    public String getCodtipomovimiento() {
        return codtipomovimiento;
    }

    public void setCodtipomovimiento(String codtipomovimiento) {
        this.codtipomovimiento = codtipomovimiento;
    }

    public String getIdentificacion() {
        return identificacion;
    }

    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    public String getTiporesponsable() {
        return tiporesponsable;
    }

    public void setTiporesponsable(String tiporesponsable) {
        this.tiporesponsable = tiporesponsable;
    }

    public void setNfactura(String nfactura) {
        this.nfactura = nfactura;
    }

    public String getNfactura() {
        return nfactura;
    }




}


