package modelo;


// Generated 26-ago-2017 15:00:10 by Hibernate Tools 4.3.1




/**
 * Perfiles generated by hbm2java
 */
public class Perfiles  implements java.io.Serializable {


     private int codperfil;
     private String descripcion;

    public Perfiles() {
    }

	
    public Perfiles(int codperfil, String descripcion) {
        this.codperfil = codperfil;
        this.descripcion = descripcion;
    }
    
    public int getCodperfil() {
        return this.codperfil;
    }
    
    public void setCodperfil(int codperfil) {
        this.codperfil = codperfil;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
 



}


