package modelo;

import java.sql.SQLException;

// Generated 26-ago-2017 15:00:10 by Hibernate Tools 4.3.1
/**
 * Responsables generated by hbm2java
 */
public class Responsables implements java.io.Serializable {

    private Ciudades ciudades;
    private Tiporesponsable tiporesponsable;
    private String identificacion;
    private String razonsocial;
    private String codtiporesposanble;
    private String codigociudad;
    private String direccion;
    private String telefono;
    private String correo;

    public Responsables() {
    }

    public Ciudades getCiudades() {
        return this.ciudades;
    }

    public void setCiudades(Ciudades ciudades) {
        this.ciudades = ciudades;
    }

    public Tiporesponsable getTiporesponsable() {
        return this.tiporesponsable;
    }

    public void setTiporesponsable(Tiporesponsable tiporesponsable) {
        this.tiporesponsable = tiporesponsable;
    }

    public String getRazonsocial() {
        return this.razonsocial;
    }

    public void setRazonsocial(String razonsocial) {
        this.razonsocial = razonsocial;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public String getCodtiporesposanble() {
        return codtiporesposanble;
    }

    public void setCodtiporesposanble(String codtiporesposanble) throws SQLException {
        tiporesponsable = new TipoResponsableDAO().obtenerTiporesponsable(codtiporesposanble);
        this.codtiporesposanble = codtiporesposanble;
    }

    public String getIdentificacion() {
        return identificacion;
    }

    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    public String getCodigociudad() {
        return codigociudad;
    }

    public void setCodigociudad(String codigociudad) {
        this.codigociudad = codigociudad;
    }

}
