package modelo;


// Generated 26-ago-2017 15:00:10 by Hibernate Tools 4.3.1

import java.sql.SQLException;




/**
 * Subcategorias generated by hbm2java
 */
public class Subcategorias  implements java.io.Serializable {


     private int codsubcategoria;
     private Categorias categorias;
     private int codcategorias;
     private String descripcion;

    public Subcategorias() {
    }

	
   
   
    public int getCodsubcategoria() {
        return this.codsubcategoria;
    }
    
    public void setCodsubcategoria(int codsubcategoria) {
        this.codsubcategoria = codsubcategoria;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public int getCodcategorias() {
        return codcategorias;
    }

    public void setCodcategorias(int codcategorias) {
        CategoriasDAO c= new CategoriasDAO();
         try {
             categorias= c.getCategorias(codcategorias);
         } catch (SQLException ex) {
             System.out.println(ex.getMessage());
         }
        this.codcategorias = codcategorias;
    }
  




}


