package modelo;


// Generated 26-ago-2017 15:00:10 by Hibernate Tools 4.3.1



/**
 * Tiporesponsable generated by hbm2java
 */
public class Tiporesponsable  implements java.io.Serializable {


     private char codtiporesponsable;
     private String descripcion;

    public Tiporesponsable() {
    }

	
   
    public char getCodtiporesponsable() {
        return this.codtiporesponsable;
    }
    
    public void setCodtiporesponsable(char codtiporesponsable) {
        this.codtiporesponsable = codtiporesponsable;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
   




}


