package modelo;


// Generated 26-ago-2017 15:00:10 by Hibernate Tools 4.3.1



/**
 * Tipomovimiento generated by hbm2java
 */
public class Tipomovimiento  implements java.io.Serializable {


     private String codtipomovimiento;
     private String descripcion;
     private String naturaleza;

    public Tipomovimiento() {
    }

	
   
   
    public String getCodtipomovimiento() {
        return this.codtipomovimiento;
    }
    
    public void setCodtipomovimiento(String codtipomovimiento) {
        this.codtipomovimiento = codtipomovimiento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNaturaleza() {
        return this.naturaleza;
    }
    
    public void setNaturaleza(String naturaleza) {
        this.naturaleza = naturaleza;
    }
 



}


