package modelo;

import java.sql.SQLException;


// Generated 26-ago-2017 15:00:10 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String codusuario;
     private String codusuario_old;
     private Perfiles perfiles;
     private  Estado estado;
     private int codperfiles;
     private String nombre;
     private String clave;
     private char codestado;

    public Usuarios() {
    }

    public Usuarios(String codusuario, Perfiles perfiles, String nombre, String clave, char estado) {
       this.codusuario = codusuario;
       this.perfiles = perfiles;
       this.nombre = nombre;
       this.clave = clave;
       this.codestado = estado;
    }
   
    public String getCodusuario() {
        return this.codusuario;
    }
    
    public void setCodusuario(String codusuario) {
        this.codusuario = codusuario;
    }
    public Perfiles getPerfiles() {
        return this.perfiles;
    }
    
    public void setPerfiles(Perfiles perfiles) {
        this.perfiles = perfiles;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public char getCodestado() {
        return this.codestado;
    }
    
    public void setCodestado(char codestado) throws SQLException {
        EstadoDAO estadoDAO= new EstadoDAO();
       estado= estadoDAO.getObtnerEstado(codestado);
        this.codestado = codestado;
    }

    public int getCodperfiles() {
        return codperfiles;
    }

    public void setCodperfiles(int codperfiles) throws SQLException {
        PerfilesDAO perfilesDAO= new PerfilesDAO();
        perfiles= perfilesDAO.getObtner(codperfiles);
        this.codperfiles = codperfiles;        
    }

    public Estado getEstado() {
        return estado;
    }

    public void setEstado(Estado estado) throws SQLException {       
        this.estado = estado;        
    }

    public String getCodusuario_old() {
        return codusuario_old;
    }

    public void setCodusuario_old(String codusuario_old) {
        this.codusuario_old = codusuario_old;
    }

}


